### PR TITLE
Set up an AWS IAM role for Vector ServiceAccount

### PR DESCRIPTION
**Pull request by MOZGIII**
Ref: https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html

This will later be used to grant Vector access to AWS resources: AWS-managed Elasticsearch, AWS S3, AWS CloudWatch, etc.

### CODE REVIEW

**Review by jszwedko — APPROVED** [review]
Seems reasonable to me!

**Comment by tustvold** [comment]
Just an FYI but having perused this codebase I'm not sure anything is actually registering the OIDC provider with IAM, which is step 2 here - https://docs.aws.amazon.com/eks/latest/userguide/enable-iam-roles-for-service-accounts.html

I'm not familiar with the eksctl provider, but something like the below should work

```
data "tls_certificate" "cluster" {
  url = aws_eks_cluster.cluster.identity.0.oidc.0.issuer
}

resource "aws_iam_openid_connect_provider" "cluster" {
  url             = aws_eks_cluster.cluster.identity.0.oidc.0.issuer
  client_id_list  = ["sts.amazonaws.com"]
  thumbprint_list = [data.tls_certificate.cluster.certificates.0.sha1_fingerprint]
}
```

**Comment by MOZGIII** [comment]
> I'm not familiar with the eksctl provider, and so it could be it is automagically doing this

It does it for us, no need to add it manually! Thanks for the suggestion though!

**Comment by MOZGIII** [comment]
As a result of this PR, we get the following env vars injected into out aggeregator `Pod`s:

```yaml
    - name: AWS_DEFAULT_REGION
      value: us-west-2
    - name: AWS_REGION
      value: us-west-2
    - name: AWS_ROLE_ARN
      value: arn:aws:iam::071959437513:role/k8s-dev-env-sa-vector
    - name: AWS_WEB_IDENTITY_TOKEN_FILE
      value: /var/run/secrets/eks.amazonaws.com/serviceaccount/token
```

Since it works as expected, I'm merging it.

**Pull request merged**
